version: '3.8'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - application
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    command: sh -c "npx prisma migrate dev && npm run dev"
    ports:
      - 4000:4000
    networks:
      - application

networks:
  application:
    driver: bridge

volumes:
  postgres:
    driver: local